# user01 = User.create(username: 'kalaven', email: 'kalaven@gmail.com', password: 'ytbW92')
# user02 = User.create(username: 'seth11', email: 'seth11@aol.com', password: 'Ghthghth!')
# user03 = User.create(username: 'profg', email: 'ericpandrews@gmail.com', password: '88341E')
# user04 = User.create(username: 'sinbad7', email: 's2777@yahoo.com', password: 'fortenbras')
# user05 = User.create(username: 'bartfan', email: 'richhenryson@gmail.com', password: 'hunter2')
# user06 = User.create(username: 'neverblue82', email: 'neverblue82@gmail.com', password: 'blueneverblue')
# user07 = User.create(username: 'thesixler', email: 'thesixler@gmail.com', password: 'Harmony8!')
# user08 = User.create(username: 'thundershirt', email: 'jvandiveer@gmail.com', password: 'coloradoBound')
# user09 = User.create(username: 'rachie88', email: 'haislip@gmail.com', password: '420aville')
# user10 = User.create(username: 'peachypie', email: 'peachypie@icloud.com', password: 'gangsta4lyfe')
# user11 = User.create(username: 'hamstermom', email: '', password: 'bigpiginthecity')
# user12 = User.create(username: 'lacesohoolihan', email: 'scottieb@ymail.com', password: 'shmeeble')
# user13 = User.create(username: 'risaspisas', email: 'risagriffin@gmail.com', password: 'rocknrollallnight')
# user14 = User.create(username: 'lilst3vie', email: 'lilst3vie', password: 'bananaproof32')
# user15 = User.create(username: 'will', email: 'willdgouda', password: 'carpetdiem')
# user16 = User.create(username: 'ugottabkittenme', email: 'kittyfluff@aol.com', password: 'kittens4eva')
# user17 = User.create(username: 'lonelyland', email: 'iamalliam@icloud.com', password: 'capnkirk')
# user18 = User.create(username: 'kitboga', email: 'kitboga@gmail.com', password: 'mrsippy')
# user19 = User.create(username: 'pjverica', email: 'pamelajverica@icloud.com', password: 'wyrmwood')
# user20 = User.create(username: 'djmankoweitz', email: 'djmankoweitz@gmail.com', password: 'strongbadisacoolguy')

user01 = User.create(username: 'kalaven', email: 'kalaven@gmail.com', password_digest: 'ytbW92')
user02 = User.create(username: 'seth11', email: 'seth11@aol.com', password_digest: 'Ghthghth!')
user03 = User.create(username: 'profg', email: 'ericpandrews@gmail.com', password_digest: '88341E')
user04 = User.create(username: 'sinbad7', email: 's2777@yahoo.com', password_digest: 'fortenbras')
user05 = User.create(username: 'bartfan', email: 'richhenryson@gmail.com', password_digest: 'hunter2')
user06 = User.create(username: 'neverblue82', email: 'neverblue82@gmail.com', password_digest: 'blueneverblue')
user07 = User.create(username: 'thesixler', email: 'thesixler@gmail.com', password_digest: 'Harmony8!')
user08 = User.create(username: 'thundershirt', email: 'jvandiveer@gmail.com', password_digest: 'coloradoBound')
user09 = User.create(username: 'rachie88', email: 'haislip@gmail.com', password_digest: '420aville')
user10 = User.create(username: 'peachypie', email: 'peachypie@icloud.com', password_digest: 'gangsta4lyfe')
user11 = User.create(username: 'hamstermom', email: '', password_digest: 'bigpiginthecity')
user12 = User.create(username: 'lacesohoolihan', email: 'scottieb@ymail.com', password_digest: 'shmeeble')
user13 = User.create(username: 'risaspisas', email: 'risagriffin@gmail.com', password_digest: 'rocknrollallnight')
user14 = User.create(username: 'lilst3vie', email: 'lilst3vie', password_digest: 'bananaproof32')
user15 = User.create(username: 'will', email: 'willdgouda', password_digest: 'carpetdiem')
user16 = User.create(username: 'ugottabkittenme', email: 'kittyfluff@aol.com', password_digest: 'kittens4eva')
user17 = User.create(username: 'lonelyland', email: 'iamalliam@icloud.com', password_digest: 'capnkirk')
user18 = User.create(username: 'kitboga', email: 'kitboga@gmail.com', password_digest: 'mrsippy')
user19 = User.create(username: 'pjverica', email: 'pamelajverica@icloud.com', password_digest: 'wyrmwood')
user20 = User.create(username: 'djmankoweitz', email: 'djmankoweitz@gmail.com', password_digest: 'strongbadisacoolguy')

Poll.create(title: "best ice cream", open: 'true', user_id: 1)
choice01 = Choice.create(name:"chocolate", poll_id: 1)
choice02 = Choice.create(name:"vanilla", poll_id: 1)
choice03 = Choice.create(name:"strawberry", poll_id: 1)
choice04 = Choice.create(name:'mint', poll_id: 1)
choice05 = Choice.create(name:'other', poll_id: 1)

Poll.create(title: 'are pants overrated', open: 'false', user_id: 1)
choice06 = Choice.create(name:'yes', poll_id: 2)
choice07 = Choice.create(name:'no', poll_id: 2)

Poll.create(title: 'who would win in a fight', open: 'true', user_id: 1)
choice08 = Choice.create(name:'Mario', poll_id: 3)
choice09 = Choice.create(name:'Sonic', poll_id: 3)
choice10 = Choice.create(name:'Megaman', poll_id: 3)

Poll.create(title: 'Day Trip Poll', open: 'true', user_id: 2)
choice11 = Choice.create(name:'Movie', poll_id: 4)
choice12 = Choice.create(name:'Theme Park', poll_id: 4)

Poll.create(title: 'Which Batman is the GOAT', open: 'true', user_id: 3)
choice13 = Choice.create(name:'Keaton', poll_id: 5)
choice14 = Choice.create(name:'Bale', poll_id: 5)
choice15 = Choice.create(name:'Affleck', poll_id: 5)
choice16 = Choice.create(name:'West', poll_id: 5)
choice17 = Choice.create(name:'Clooney', poll_id: 5)
choice18 = Choice.create(name:'Kilmer', poll_id: 5)

Poll.create(title: 'Which Joker is the GOAT', open: 'true', user_id: 3)
choice19 = Choice.create(name:'Nicholson', poll_id: 6)
choice20 = Choice.create(name:'Ledger', poll_id: 6)
choice21 = Choice.create(name:'Hamill', poll_id: 6)
choice22 = Choice.create(name:'Leto', poll_id: 6)

Poll.create(title: 'Would you rather...', open: 'false', user_id: 4)
choice23 = Choice.create(name:'Fight 1 horse sized duck', poll_id: 7)
choice24 = Choice.create(name:'fight 100 duck sized horses', poll_id: 7)

Poll.create(title: "what is next months focus?", open: 'true', user_id: 6)
choice25 = Choice.create(name:'beat the competition to market', poll_id: 8)
choice26 = Choice.create(name:'earnings over interest', poll_id: 8)
choice27 = Choice.create(name:'capitalize on momentum', poll_id: 8)

Poll.create(title: 'Is it time yet?', open: 'false', user_id: 9)
choice28 = Choice.create(name:'sure', poll_id: 9)
choice29 = Choice.create(name:'what', poll_id: 9)
choice30 = Choice.create(name:'stop', poll_id: 9)

Poll.create(title: 'choose one', open: 'true', user_id: 10)
choice31 = Choice.create(name:'mustard', poll_id: 10)
choice32 = Choice.create(name:'ketchup', poll_id: 10)
choice33 = Choice.create(name:'mayonaise', poll_id: 10)
choice34 = Choice.create(name:'a million dollars', poll_id: 10)

Poll.create(title: 'Which season of stranger things is overall the best so far?', open: 'true', user_id: 12)
choice35 = Choice.create(name:'Season 1', poll_id: 11)
choice36 = Choice.create(name:'Season 2', poll_id: 11)
choice37 = Choice.create(name:'Season 3', poll_id: 11)

user01.choices.push(choice16, choice22, choice30, choice35)
user02.choices.push(choice04, choice14, choice27, choice36)
user03.choices.push(choice01, choice13, choice21, choice26, choice34)
user04.choices.push(choice02, choice27, choice28, choice34, choice35)
user05.choices.push(choice03, choice22, choice26, choice37)
user06.choices.push(choice02, choice06, choice08, choice17)
user07.choices.push(choice04, choice27, choice30, choice35)
user08.choices.push(choice05, choice07, choice18, choice25)
user09.choices.push(choice03, choice06, choice13, choice28, choice34)
user10.choices.push(choice03, choice14, choice19, choice27, choice37)
user11.choices.push(choice04, choice17, choice27, choice36)
user12.choices.push(choice03, choice30, choice32, choice35)
user13.choices.push(choice02, choice09, choice17, choice20, choice35)
user14.choices.push(choice04, choice16, choice27, choice30, choice37)
user15.choices.push(choice04, choice13, choice19, choice25, choice34)
user16.choices.push(choice03, choice10, choice21, choice26, choice35)
user17.choices.push(choice02, choice14, choice20, choice26, choice30)
user18.choices.push(choice01, choice13, choice25, choice30, choice35)
user19.choices.push(choice03, choice14, choice26, choice30, choice37)
user20.choices.push(choice03, choice07, choice13, choice20, choice25, choice34)

# choice01.users.push(user03, user18)
# choice02.users.push(user04, user06, user13, user17)
# choice03.users.push(user05, user09, user10, user12, user16, user19, user20)
# choice04.users.push(user02, user07, user11, user14, user15)
# choice05.users.push(user08)

# choice06.users.push(user05, user09)
# choice07.users.push(user08, user20)

# choice08.users.push(user06)
# choice09.users.push(user13)
# choice10.users.push(user16)

# choice13.users.push(user03, user09, user15, user18, user20)
# choice14.users.push(user02, user10, user17, user19)
# choice16.users.push(user01, user14)
# choice17.users.push(user06, user11, user13)
# choice18.users.push(user08)

# choice19.users.push(user10, user15)
# choice20.users.push(user13, user17, user20)
# choice21.users.push(user03, user16)
# choice22.users.push(user01, user05)

# choice25.users.push(user08, user15, user18, user20)
# choice26.users.push(user03, user05, user16, user17, user19)
# choice27.users.push(user02, user04, user07, user10, user11, user14)

# choice28.users.push(user04, user09)
# choice30.users.push(user01, user08, user12, user14, user17, user18, user19)

# choice32.users.push(user12)
# choice34.users.push(user03, user04, user09, user15, user20)

# choice35.users.push(user01, user04, user07, user12, user13, user16, user18)
# choice36.users.push(user02, user11)
# choice37.users.push(user05, user10, user14, user19)